---
title: "Lista 04"
author: "Mariana Zamith Feltrin"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "me315.sqlite")
```

```{sql connection=con}
SELECT * FROM PRESERVE
```

```{sql connection=con}
SELECT * FROM EMPLOYEE
```

## Exercício 1

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE PNO IN (2, 4, 6, 8, 10)
```

## Exercício 2

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE PNAME NOT IN ('DANCING PRAIRIE', 'MULESHOE RANCH', 'MCELWAIN-OLSEN', 'TATKON')
```

## Exercício 3

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE PNO BETWEEN 3 AND 10
```

## Exercício 4

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE PNO NOT BETWEEN 3 AND 10
```

## Exercício 5

```{sql connection=con}
SELECT STATE, PNO, ACRES FROM PRESERVE
WHERE STATE NOT IN ('AZ', 'MT') 
AND ACRES NOT BETWEEN 50 AND 800
ORDER BY PNO DESC
```

## Exercício 6

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE 'D%'
```

## Exercício 7

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%TOWN%'
```

## Exercício 8

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%PRAIRIE'
```

## Exercício 9

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%ING%'
```

## Exercício 10

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%E'
```

## Exercício 11

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%ME%'
```

## Exercício 12

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '%M%E%'
```

## Exercício 13

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '_A%'
```

## Exercício 14

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE PNAME LIKE '% %'
```

## Exercício 15

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE (PNAME LIKE '%FARM%') OR (PNAME LIKE '%SWAMP%') OR (PNAME LIKE '%PRAIRIE%')
```

## Exercício 16

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE (PNAME LIKE '%.%') OR (PNAME LIKE '%-%')
```

## Exercício 17

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE (PNAME LIKE '____R%') OR (PNAME LIKE '%PRAIRIE%')
```

## Exercício 18

```{sql connection=con}
SELECT * FROM EMPLOYEE
WHERE DNO IN (10, 40)
```

## Exercício 19

```{sql connection=con}
SELECT * FROM EMPLOYEE
WHERE DNO NOT IN (10, 40)
```

## Exercício 20

```{sql connection=con}
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 500 AND 2000
```

## Exercício 21

```{sql connection=con}
SELECT * FROM EMPLOYEE
WHERE SALARY NOT BETWEEN 500 AND 2000
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
